# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jumpy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='jumpy.proto',
  package='jumpy',
  syntax='proto3',
  serialized_options=b'\n\rio.grpc.jumpyB\nJumpyProtoP\001\242\002\005Jumpy',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bjumpy.proto\x12\x05jumpy\"\x12\n\x04Page\x12\n\n\x02id\x18\x01 \x01(\x05\"3\n\x08\x43\x61tegory\x12\x0c\n\x04link\x18\x01 \x01(\t\x12\x19\n\x04page\x18\x02 \x03(\x0b\x32\x0b.jumpy.Page\"B\n\x0eProductRequest\x12!\n\x08\x63\x61tegory\x18\x01 \x01(\x0b\x32\x0f.jumpy.Category\x12\r\n\x05index\x18\x02 \x01(\x05\"v\n\x0fProductResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04link\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0e\n\x06rating\x18\x04 \x01(\x01\x12\x13\n\x0brated_sales\x18\x05 \x01(\t\x12\x13\n\x0bseller_name\x18\x06 \x01(\t2\xac\x02\n\x14JumiaProductsFetcher\x12=\n\nGetProduct\x12\x15.jumpy.ProductRequest\x1a\x16.jumpy.ProductResponse\"\x00\x12@\n\x0bGetProducts\x12\x15.jumpy.ProductRequest\x1a\x16.jumpy.ProductResponse\"\x00\x30\x01\x12G\n\x12GetCheapestProduct\x12\x15.jumpy.ProductRequest\x1a\x16.jumpy.ProductResponse\"\x00(\x01\x12J\n\x13GetCheapestProducts\x12\x15.jumpy.ProductRequest\x1a\x16.jumpy.ProductResponse\"\x00(\x01\x30\x01\x42%\n\rio.grpc.jumpyB\nJumpyProtoP\x01\xa2\x02\x05Jumpyb\x06proto3'
)




_PAGE = _descriptor.Descriptor(
  name='Page',
  full_name='jumpy.Page',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='jumpy.Page.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=40,
)


_CATEGORY = _descriptor.Descriptor(
  name='Category',
  full_name='jumpy.Category',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='link', full_name='jumpy.Category.link', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='page', full_name='jumpy.Category.page', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=93,
)


_PRODUCTREQUEST = _descriptor.Descriptor(
  name='ProductRequest',
  full_name='jumpy.ProductRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='jumpy.ProductRequest.category', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='index', full_name='jumpy.ProductRequest.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=161,
)


_PRODUCTRESPONSE = _descriptor.Descriptor(
  name='ProductResponse',
  full_name='jumpy.ProductResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='jumpy.ProductResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='link', full_name='jumpy.ProductResponse.link', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='jumpy.ProductResponse.price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rating', full_name='jumpy.ProductResponse.rating', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rated_sales', full_name='jumpy.ProductResponse.rated_sales', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seller_name', full_name='jumpy.ProductResponse.seller_name', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=281,
)

_CATEGORY.fields_by_name['page'].message_type = _PAGE
_PRODUCTREQUEST.fields_by_name['category'].message_type = _CATEGORY
DESCRIPTOR.message_types_by_name['Page'] = _PAGE
DESCRIPTOR.message_types_by_name['Category'] = _CATEGORY
DESCRIPTOR.message_types_by_name['ProductRequest'] = _PRODUCTREQUEST
DESCRIPTOR.message_types_by_name['ProductResponse'] = _PRODUCTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Page = _reflection.GeneratedProtocolMessageType('Page', (_message.Message,), {
  'DESCRIPTOR' : _PAGE,
  '__module__' : 'jumpy_pb2'
  # @@protoc_insertion_point(class_scope:jumpy.Page)
  })
_sym_db.RegisterMessage(Page)

Category = _reflection.GeneratedProtocolMessageType('Category', (_message.Message,), {
  'DESCRIPTOR' : _CATEGORY,
  '__module__' : 'jumpy_pb2'
  # @@protoc_insertion_point(class_scope:jumpy.Category)
  })
_sym_db.RegisterMessage(Category)

ProductRequest = _reflection.GeneratedProtocolMessageType('ProductRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTREQUEST,
  '__module__' : 'jumpy_pb2'
  # @@protoc_insertion_point(class_scope:jumpy.ProductRequest)
  })
_sym_db.RegisterMessage(ProductRequest)

ProductResponse = _reflection.GeneratedProtocolMessageType('ProductResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTRESPONSE,
  '__module__' : 'jumpy_pb2'
  # @@protoc_insertion_point(class_scope:jumpy.ProductResponse)
  })
_sym_db.RegisterMessage(ProductResponse)


DESCRIPTOR._options = None

_JUMIAPRODUCTSFETCHER = _descriptor.ServiceDescriptor(
  name='JumiaProductsFetcher',
  full_name='jumpy.JumiaProductsFetcher',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=284,
  serialized_end=584,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProduct',
    full_name='jumpy.JumiaProductsFetcher.GetProduct',
    index=0,
    containing_service=None,
    input_type=_PRODUCTREQUEST,
    output_type=_PRODUCTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetProducts',
    full_name='jumpy.JumiaProductsFetcher.GetProducts',
    index=1,
    containing_service=None,
    input_type=_PRODUCTREQUEST,
    output_type=_PRODUCTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCheapestProduct',
    full_name='jumpy.JumiaProductsFetcher.GetCheapestProduct',
    index=2,
    containing_service=None,
    input_type=_PRODUCTREQUEST,
    output_type=_PRODUCTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCheapestProducts',
    full_name='jumpy.JumiaProductsFetcher.GetCheapestProducts',
    index=3,
    containing_service=None,
    input_type=_PRODUCTREQUEST,
    output_type=_PRODUCTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_JUMIAPRODUCTSFETCHER)

DESCRIPTOR.services_by_name['JumiaProductsFetcher'] = _JUMIAPRODUCTSFETCHER

# @@protoc_insertion_point(module_scope)
